workflows:
  android-workflow:
    name: Android APK Build
    environment:
      flutter: stable
    scripts:
      - name: Clean old Android
        script: |
          rm -rf android
          rm -rf build
      - name: Create fresh Flutter Android
        script: |
          flutter create --platforms=android .
      - name: Build Release APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk